spring.application.name=masterspringboot


# URL kết nối CSDL (thay localhost:5432 và my_database bằng cổng và tên database của bạn)
spring.datasource.url=jdbc:postgresql://localhost:5432/masterspringboot
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate JPA
# ddl-auto: update (tự động tạo/sửa bảng theo Entity), validate, hoặc none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false